name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  Test:
    runs-on: ubuntu-latest
    environment: Airtable Testing
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Gradle setup
        uses: gradle/gradle-build-action@v2

      - name: Gradle test
        run: ./gradlew test
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}

      - uses: codecov/codecov-action@e3c560433a6cc60aec8812599b7844a7b4fa0d71
        with:
          fail_ci_if_error: true
