name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Gradle setup
        uses: gradle/gradle-build-action@v2

      - name: Gradle build
        run: ./gradlew build

      - name: Gradle test
        run: ./gradlew test
