name: Governance Labeler

on:
  pull_request_target:
    types: [ opened, edited, synchronize ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@67208f475e36fc4f95e3d5a2d4e450433f288be8
        with:
          config-path: .github/labeler.yml
