name: Publish

on:
  release:
    types: [ published ]


jobs:
  main:
    name: "Maven Central"
    runs-on: ubuntu-latest
    environment: Maven Central Publishing
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Gradle setup
        uses: gradle/gradle-build-action@v2

      - run: ./gradlew uploadArchives closeAndPromoteRepository
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
